/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  AttendanceRecord as PrismaAttendanceRecord,
  User as PrismaUser,
} from "@prisma/client";

export class AttendanceRecordServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AttendanceRecordCountArgs, "select">
  ): Promise<number> {
    return this.prisma.attendanceRecord.count(args);
  }

  async attendanceRecords<T extends Prisma.AttendanceRecordFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.AttendanceRecordFindManyArgs>
  ): Promise<PrismaAttendanceRecord[]> {
    return this.prisma.attendanceRecord.findMany<Prisma.AttendanceRecordFindManyArgs>(
      args
    );
  }
  async attendanceRecord<T extends Prisma.AttendanceRecordFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.AttendanceRecordFindUniqueArgs>
  ): Promise<PrismaAttendanceRecord | null> {
    return this.prisma.attendanceRecord.findUnique(args);
  }
  async createAttendanceRecord<T extends Prisma.AttendanceRecordCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AttendanceRecordCreateArgs>
  ): Promise<PrismaAttendanceRecord> {
    return this.prisma.attendanceRecord.create<T>(args);
  }
  async updateAttendanceRecord<T extends Prisma.AttendanceRecordUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.AttendanceRecordUpdateArgs>
  ): Promise<PrismaAttendanceRecord> {
    return this.prisma.attendanceRecord.update<T>(args);
  }
  async deleteAttendanceRecord<T extends Prisma.AttendanceRecordDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.AttendanceRecordDeleteArgs>
  ): Promise<PrismaAttendanceRecord> {
    return this.prisma.attendanceRecord.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.attendanceRecord
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
